config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  get 'frinds/create'
  get 'frinds/update'
  get 'frinds/destroy'
  get 'friends/index'
  resources :friends
  devise_for :users
  get 'welcome/index'
  root 'frinds#welcome'
  get "frinds/myfriend"
  get "frinds/myprofile"
  get "frinds/pending"
  resources :users
  get 'layouts/application'
  

  #root 'frinds#whatever'

  resources :frinds, only: [:create, :update, :destroy]
  get 'frinds/whatever'

  resources :posts

  resources :posts do
    resources :comments do
      resources :replies
    end  
  end

   #get 'auth/:provider/callback', to: 'sessions#create'
   match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
   match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
   post '/likes' => 'likes#create', as: :like_create
   post '/dislikes' => 'likes#dislike', as: :dislike_create
end

app/models/frind.rb
class Frind < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :frind, class_name: "User", foreign_key: :friend_id, optional: true
	
	def self.search(search)
    where("title LIKE ?" , "%#{search}%") 
  end
end

app/controllers/frinds_controller.rb
class FrindsController < ApplicationController
	before_action :authenticate_user!

	def index
    @frinds = Frind.all
    if params[:search]
      @frinds = Frind.search(params[:search]).order("created_at DESC")
    else
      @frinds = Frind.all.order("created_at DESC")
    end
  end

	def create
		
	  @frind = current_user.frinds.build(friend_id: params[:friend_id])
	  @frind.accepted = false
	  if @frind.save
	    flash[:notice] = "Friend requested."
	    redirect_to "/frinds/whatever"
	  else
	    flash[:error] = "Unable to request frind."
	    redirect_to "/frinds/whatever"
	  end
	end

	def update
 		@frind = Frind.find_by(id: params[:id])
		@frind.update(accepted: true)
    if @frind.save
	    redirect_to root_url, notice: "Successfully confirmed friend!"
	  else
	    redirect_to root_url, notice: "Sorry! Could not confirm friend!"
	  end
	end

	def destroy
		@frind = Frind.find_by(id: params[:id])
	  @frind.destroy
	  flash[:notice] = "Removed frind."
	  redirect_to "/frinds/whatever"
	end

  def whatever
  	@users= User.all
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order("created_at DESC")
    end
  end
  def myprofile
  end	
   
  def myfriend
  	
  	user = current_user
   	#@users = user.frinds.where(accepted: true)
   	
   	# friends_ids = user.frinds.where(accepted: true).pluck(:friend_id)
   	# received_friends_ids = user.received_frinds.where(accepted: true).pluck(:friend_id)

   	# friends_ids = friends_ids + received_friends_ids
   	# @friends = User.where(:id => friends_ids)
   	@friends = user.friends
	end
	def pending
		@users = current_user
		@users = current_user.pending_friends
	end

  def frind_params
	  params.require(:frinds).permit(:friend_id, :user_id, :accepted)
	end 
end

app/helpers/frinds_helper.rb
module FrindsHelper
end

app/views/frinds/create.html.erb
<h1>Frinds#create</h1>
<p>Find me in app/views/frinds/create.html.erb</p>

app/views/frinds/destroy.html.erb
<h1>Frinds#destroy</h1>
<p>Find me in app/views/frinds/destroy.html.erb</p>

app/views/frinds/myfriend.html.erb
<div class="table-responsive">          
  <table class="table datatable table-bordered">
    <thead>
      <tr class="bg-primary">
        <th>Friends</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.friends.each do |friend| %>
        <tr>
          
        <td><% if friend.user == current_user %>
          <% user = friend.frind %>
        <% else %>
          <% user = friend.user %>
        <% end %>
        <% if user.present? %>
          <hr>
        <%= user.email %></td>
        <td><%= link_to "Unfriend", frind_path(id: friend.id), method: :delete, class: "btn btn-primary" %></td>
         
         <%end%> 
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/frinds/myprofile.html.erb
<div class="table-responsive">          
  <table class="table datatable table-bordered">
    <thead>
      <tr class="bg-primary">
        <th>Email</th>
        <th>Name</th>
        <th>Image</th>
        <th>Action</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <% if current_user.present? %> 
          <td>
            <%= current_user.email %></td>
            <td><%= current_user.firstname %></td>
            <td><%= image_tag current_user.image_url.to_s, style:"height: 70px; width:70px;" %> </td>
            <td><%= link_to "edit profile", edit_user_registration_path(@user), class: "btn btn-primary"%></td>
            <td><%= link_to "Back", :back, class: "btn btn-primary" %>
            </td>
        <%end%>  
      </tr>
    </tbody>
  </table>
</div>

app/views/frinds/pending.html.erb
<div class="table-responsive">          
  <table class="table datatable table-bordered">
    <thead>
      <tr class="bg-primary">
        <th>Email</th>
        <th>Action</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
     <% current_user.pending_friends.each do |f_request| %>
        <tr>
	        <td><%= f_request.user.try(:email) %></td>
	        <td><%= link_to "Accept", frind_path(id: f_request.id), method: "put", class: "btn btn-primary" %></td>
	        <td><%= link_to "Decline", frind_path(id: f_request.id), method: :delete, class: "btn btn-primary" %></p></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/frinds/update.html.erb
<h1>Frinds#update</h1>
<p>Find me in app/views/frinds/update.html.erb</p>

app/views/frinds/welcome.html.erb
<br><br><br>
<html>
  <head>
  </head>
  <body>
	
  <h1 align="center">
    <div id=rcorners1 align="center">
      <%#= link_to 'all users', "frinds/whatever",  class: "btn btn-primary"%>
      <%#= link_to 'friends', "frinds/myfriend",  class: "btn btn-primary"%>
      <%#= link_to 'pending request', "frinds/myfriend", class: "btn btn-primary"%>
    </div>
  </h1>
</body>

app/views/frinds/whatever.html.erb
<html>
  <body>
    <% if @users.blank? %>
      <h4>Result can not found <%= params[:search] %>.</h4>
    <% end %>
  </body>
</html>

<div class="table-responsive">          
  <table class="table datatable table-bordered">
    <thead>
      <tr class="bg-primary">
        <th>Name</th>
        <th>Email</th>
        <th>Image</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
     <% @users.where.not(id: current_user.id).each do |user| %>
        <tr>
          
        <td><%= user.firstname %></td>
        <td><%= user.email %></td>
        <td><% if user.image.present? %>
                <%= image_tag user.image_url.to_s, style:"height: 70px; width:70px;" %>
            <%end%>    
                  
        </td>
        <td><% if Frind.where(user_id: [current_user.id, user.id],friend_id: [current_user.id, user.id], accepted: false).present? %>
                Request Sent
                <% elsif Frind.where(user_id: [current_user.id, user.id],friend_id: [current_user.id, user.id], accepted: true).present? %>
                Friend
                <%else %>
                <%= link_to "Add Friend", frinds_path(friend_id: user), method: :post, class: "btn btn-primary" %>
                <%if current_user && current_user.try(:admin?) %>
                <%= link_to "Decline", user_path(id: user.id), method: :delete, class: "btn btn-primary" %>
                  <% end %>
                  <%if current_user && current_user.try(:moderator?) %>
                <%= link_to "Edit", edit_user_path(id: user.id), class: "btn btn-primary" %>
                <% end %>
                </p>
              </td>
         
         <%end%> 
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<h1 align="center">
    <%= link_to "Back", :back, class: "btn btn-primary" %></h1>
<!-- <table border="2px" align="center" width="30%">
      <td>  
        <h3 align="center">Your Pending Requests</h3>
        <ul>
          <%# current_user.pending_friends.each do |f_request| %>
            <li>
              <p align="center">
                
              <%#= f_request.user.try(:email) %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              <%#= link_to "Accept", frind_path(id: f_request.id), method: "put", class: "btn btn-primary" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
               
              <%#= link_to "Decline", frind_path(id: f_request.id), method: :delete, class: "btn btn-primary" %></p>
            </li>
          <%# end %>
        </ul>
  </td>
</table> -->