config/routes.rb
Rails.application.routes.draw do
  
  resources :categories
  get 'frinds/create'
  get 'frinds/update'
  get 'frinds/destroy'
  get 'friends/index'
  resources :friends
  devise_for :users
  get 'welcome/index'
  root 'frinds#welcome'
  get "frinds/myfriend"
  get "frinds/myprofile"
  get "frinds/pending"
  resources :users
  get 'layouts/application'
  

  #root 'frinds#whatever'

  resources :frinds, only: [:create, :update, :destroy]
  get 'frinds/whatever'

  resources :posts

  resources :posts do
    resources :comments do
      resources :replies
    end  
  end

   #get 'auth/:provider/callback', to: 'sessions#create'
   match '/auth/:provider/callback', :to => 'sessions#create', via: [:get, :post]
   match '/auth/failure', :to => 'sessions#failure', via: [:get, :post]
   post '/likes' => 'likes#create', as: :like_create
   post '/dislikes' => 'likes#dislike', as: :dislike_create
end

app/models/post.rb
class Post < ApplicationRecord
	belongs_to :user
	has_many :comments, dependent: :destroy
	belongs_to :category
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    # byebug
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:user_id, :topic, :category_id, :post_text, :attachment, :visibility, :expiration_date)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class='container-fluid login bg-dark-grey login-form' >
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

        <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group text-center">
      <h3 class="mb40"></h3>
    </div> 
    <div class="login-white-box">
      <div class="form-group">
        <%= form.hidden_field :user_id, :value => current_user.id %>
      </div>  
      <div class="form-group">
      
      <%#= form.label :Topic %>
      <%#= form.text_area :topic, class: 'form-control input-form-control' %>
      <%= form.select(:category_id, Category.all.collect {|s| [s.name, s.id]}, {:include_blank => "Select"}, class: "select", "data-errormessage-value-missing"=>"Please select category") %>
    </div><br>
      <div class="form-group">
                            
        
        <%= form.label :Headlines %>
        <%= form.text_area :post_text, class: 'form-control input-form-control' %>
      </div>
      <div class="form-group">
      <%= form.label :Description %>
      <%= form.text_area :attachment, class: 'form-control input-form-control' %>
      </div>
      
      <div class="form-group row">
        <div class="col-md-12">
          <div class="pull-left">
             <div class="actions">
              <%= form.submit %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>  
<%#= f.text_field "category", :value=>select_type(f, "category_id", "Category"), class: "selectInput" ,:id=>'category', name: "category_name_second"%>
                <%#= f.select(:category_id, Category.all.collect {|s| [s.name, s.id]}, {:include_blank => "Select"}, "data-validation-engine"=>"validate[required]", class: "select", "data-errormessage-value-missing"=>"Please select category") %>

app/views/posts/_polymorphic_form.html.erb
<!-- Post form for group and community -->
<div class="clearfix innerWIdth550 tac ">
  <%= nested_form_for([object, @post], html: {class: "", :id => "form-id"}) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation" class="login errorMSg">
      <!-- <h2><%#= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2> -->
      <ul>
        <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </div>
    <% end %>
    <div class="clearfix whiteBox connectionRow borderTpBlue">
      <div class="clearfix cmntRow tal">
        <div class="clearfix userInfo posRel">
          <div class="clearfix  "></div>
          <a href="<%= profile_path(current_user)%>" class="userImg"><img src="<%= current_user.try(:img) %>" alt=""></a>
          <a href="<%= profile_path(current_user)%>" class="userNAme font14 mt23Final"> <%= current_user.screen_name %> Start a conversation with your <%=object.class.name.downcase rescue nil%></a> <br>
        </div>
      </div>
    </div>
    <div class="clearfix whiteBox mt-1  mb10  ">
      <!-- render upload for image, file, url uploading -->
        <%=render 'layouts/shared/upload', f: f, obj: @post %>
      <!-- render upload for image, file, url uploading -->      
    </div>
    <div class="clearfix whiteBox">
      <div class="clearfix formOuterPost tal">
        <div class="col-sm-6 pr10">
          <label>Select Category</label>
          <div class="selctFormBox">
            <%= f.text_field "category", :value=>select_type(f, "category_id", "Category"), class: "selectInput" ,:id=>'category', name: "category_name_second"%>
            <%= f.select(:category_id, Category.all.collect {|s| [s.name, s.id]}, {:include_blank => "Select"}, "data-validation-engine"=>"validate[required]", class: "select")  %>
          </div>
          <div id="category_name_error"></div>
        </div>
        <div class="col-sm-6 pl10">
          <label>Type Topic</label>
          <!-- <div class="selctFormBox"> -->
          <%#= f.hidden_field :topic_id, :value=>'Select', class: " selectInputField" %>
          <%#= f.text_field "topic_id", :value=>'Select', class: "selectInput" ,:id=>'topic'%>
          <%#= f.select("topic_id", Topic.all.collect {|s| [s.name, s.id]}, {}, class: "select")  %>
          <!-- </div> -->
          <%= f.text_field :topic, :id=>"topic", "data-validation-engine"=>"validate[required]", class: "inputTextW small", placeholder: "Topics" %>
        </div>
        <div class="col-sm-12">
          <label class="font20">Write Your Headline</label>
          <%= f.text_field :title, "data-validation-engine"=>"validate[required]", class: "inputTextW small", placeholder: "Please write headline here...." %>
        </div>
        <div class="col-sm-12">
          <label class=""><%= f.label "Write Something" %></label>
          <%= f.text_area :description, class: "inputTextW small", placeholder: "Please write description here...." %>
        </div>
        <div class="col-sm-12">
          <%= f.submit "Save Post", class: "blueBtn common_submit" %>
          <a href="/dashboard" class="grayBtn">Cancel</a>  
        </div>
      </div>
    </div>
    <br>
  <% end %>
</div>
<!-- Post form for group and community -->

app/views/posts/_post.html.erb
<li>
  <div class="lft"><a  href="#"><%= image_tag current_user.profile.try(:image) %></a></div>
  <div class="rgt">
    <div class="top">
      <div class="hd">
        <%=link_to post.title, post %>
        <%if post.user_id==current_user.id%>
        <img src="<%= asset_path("images/edit_icon-img.png") %>" onclick = '$(".edit-post-form-<%= post.id%>").toggle();' >
        <% end %>
        <div class="edit-post-form-<%= post.id %>" style="display:none;">
          <div class="hitGoing">
            <div class="sendBox">                    
              <%= form_for(post, :remote=>true) do |f| %>
              <%= f.text_field :title, :class=>"input" %>
              <%= f.submit "Update", :class=>"btn"%>
              <% end %>
            </div>
          </div>
        </div>
        <%if post.user_id==current_user.id%>
          <%= link_to image_tag('delete-icon.png'), post, method: :delete, data: { confirm: 'Are you sure?' } %>
        <%end%>
      </div>
      <div class="info"><span></span></div>
      <%if post.user_id!=current_user.id%>
        <div class="cheerNow">
          <%if current_user.following?(post.user)%>
          <td class="following-button-<%= post.user_id %>"><%= link_to "UnFollow", follow_path(:follower_id => post.user_id), :method => :post , :class=>"transition addFriend", :remote=>true ,:class=>'replyBtn' %></td>
          <% else %>
          <td class="following-button-<%=post.user_id %>"><%= link_to "Follow", follow_path(:follower_id => post.user_id), :method => :post , :class=>"transition addFriend", :remote=>true,:class=>'replyBtn' %></td>
          <%end%>
        </div>
      <%end%>  
    </div>
    <div class="links">
      <span class="like-<%= post.id%>">
      (<%=post.likes.count%>)<%= link_to "Like", post_likes_path(post), method: :post, remote: true%>
      </span>
      <span class="hide-show-comment" onclick= "$('#commentBox-<%= post.id%>').toggle();">(<%=post.comments.count%>)Comment</span>
    </div>
    <div class="lists-comments-<%= post.id%>">
      <% post.comments.each do |comment|%>
      <!--           <div class="comments-box"><%#= comment.body %></div>
        -->
      <div class="comment-box-<%=comment.id%>">
        <!-- render comments/show -->
        <%= render 'comments/show' , :comment => comment %>
        <!-- render comments/show -->
      </div>
      <%end%>
    </div>
    <div class="commentBox commentBox-<%= post.id%>" style="display :none" id="commentBox-<%= post.id%>">
      <%= form_for([post, post.comments.build], :remote=>true) do |f| %>
      <%= f.text_field :body, :class=>"formInput" %>
      <%#= f.submit "Comment", :class=>"btn"%>
      <%end%>
    </div>
  </div>
  <div class="clr"></div>
</li>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1 align="center"><%= link_to 'New Post', new_post_path, class: "btn btn-primary" %><br/><br /></h1>
<section class="container">
  <div  style="text-align: center;" class="row">
    <% @posts.each do |post| %>
      <div class="col-md-4">
        <a href="/posts/<%= post.id %>">
          <div class="card mb-4 box-shadow card_size">
            <div class="card-header text-center">
              <h4><%= post.topic %></h4>
            </div>
            <div class="post_size " >
              <p>
                <h5><%= post.post_text %></h5>
              </p>
            </div>
             <div class="post_size text-center card-header">
              <p>
                <h5><%= post.attachment %></h5>
              </p>
            </div>
          </div>
        </a>
        <% if post.user_id == current_user.id %>
      <%= link_to 'Edit', edit_post_path(post), class: "btn btn-primary" %>
      <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
      <%end%>
      </div>
      
    <% end %>
  </div>
</section>




<style type="text/css">
  .card_size
  {
    width: 297px;
    /*height: 150px;*/
  }
  .h4
  {
    font-size: 22px;
    font-style: normal;
    font-weight: 500;
    line-height: 32px;
  }
  .row
  {

    display: flex;
    flex-wrap: wrap;
    margin-right: -15px;
    margin-left: -15px;
  }
  .container {
    max-width: 940px;
    /*background-color: grey;*/
  }
  .card-header {
    padding: 0.75rem 1.25rem;
    margin-bottom: 0;
    background-color: rgba(0,0,0,0.03);
    border-bottom: 1px solid rgba(0,0,0,0.125);
  }
  .card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 1px solid rgba(0,0,0,0.125);
    border-radius: 0.25rem;
  }
  .mb-4, .my-4 {
    margin-bottom: 1.5rem !important;
  }
  .post_size
  {
    height: 100px;

  }
</style>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/previous_comments.js.erb
$("#last_post_comment_<%=@post.id%>").prepend("<%=j render(partial: 'comments/comments_view', locals: { comments: @comments, page: params[:page], object: @post, from: 'post_index' })%>");
$("#prev_comments_<%=@post.id%>").html("<%=j render(partial: 'layouts/shared/prev_comments', locals: { comments: @comments, page: params[:page], object: @post})%>");

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <div class="col-sm-12 well">
    <h1><%= @post.topic %></h1>
    <h2><%= @post.post_text %></h2>
    <h5><%= @post.attachment %></h5>
    
  </div>
</div>

<!-- <p>
  <strong>User:</strong>
  <%#= @post.user_id %>
</p> -->

<!-- <p>
  <strong>Topic:</strong>
  <%#= @post.topic %>
</p>

<p>
  <strong>Post text:</strong>
  <%#= @post.post_text %>
</p>

<p>
  <strong>Attachment:</strong>
  <%#= @post.attachment %>
</p>

<p>
  <strong>Visibility:</strong>
  <%#= @post.visibility %>
</p>

<p>
  <strong>Expiration date:</strong>
  <%#= @post.expiration_date %>
</p> -->

<h2>Comments</h2>
<%= render @post.comments %>
 
<!-- <h2>Add a comment:</h2> -->
<%= render 'comments/form' %>
<% if @post.user_id == current_user.id %>
  <%= link_to 'Edit', edit_post_path(@post) %> |
<%end%>  
<%= link_to 'Back', posts_path %>

<style type="text/css">
  .well {
    min-height: 20px;
    padding: 19px;
    margin-bottom: 20px;
    background-color: #f5f5f5;
    border: 2px solid #e3e3e3;
    border-radius: 4px;
  }
  .container {
    max-width: 985px;
  }
</style>